server:
  port: 20000
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  jmx:
    default-domain: huhuiyu.springbase.template
  web: 
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 10MB
      max-request-size: 10MB